package studio.halbear.hem.procedures;

import studio.halbear.hem.HemMod;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.EntityTypeTags;
import net.minecraft.entity.Entity;

import java.util.Map;

public class HotAirBalloonUIDisplayOverlayIngame2Procedure {

	public static boolean executeProcedure(Map<String, Object> dependencies) {
		if (dependencies.get("entity") == null) {
			if (!dependencies.containsKey("entity"))
				HemMod.LOGGER.warn("Failed to load dependency entity for procedure HotAirBalloonUIDisplayOverlayIngame2!");
			return false;
		}
		Entity entity = (Entity) dependencies.get("entity");
		if (EntityTypeTags.getCollection().getTagByID(new ResourceLocation("minecraft:skeletons")).contains(entity.getType())) {
			return true;
		}
		return true;
	}
}
