package studio.halbear.hem_custom.registry;

import net.minecraft.entity.EntityClassification;
import net.minecraft.entity.EntityType;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.event.entity.EntityAttributeCreationEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import studio.halbear.hem_custom.vehicles.Entity.Aeroplane;


@Mod.EventBusSubscriber(modid = "hem", bus = Mod.EventBusSubscriber.Bus.MOD)
public class ModEntities {

    public static final EntityType<Aeroplane> AEROPLANE = null;

    @SubscribeEvent
    public static void registerEntities(final RegistryEvent.Register<EntityType<?>> event) {
        EntityType<Aeroplane> entity = EntityType.Builder.create(Aeroplane::new, EntityClassification.MISC)
                .size(2, 1.5F).build(new ResourceLocation(ModStatics.MOD_ID, "aeroplane").toString());
        entity.setRegistryName(new ResourceLocation(ModStatics.MOD_ID, "aeroplane"));
        event.getRegistry().register(entity);
    }

    @SubscribeEvent
    public static void registerAttributes(final EntityAttributeCreationEvent event) {
        //if an entity has attributes, register them here
    }
}
