package studio.halbear.hem.procedures;

import studio.halbear.hem.block.FallenLeavesBlock;
import studio.halbear.hem.HemMod;

import net.minecraft.world.IWorld;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.BlockTags;
import net.minecraft.block.Blocks;

import java.util.Map;

public class FluorescentLeavesParticlesAdditionalParticleExpiryConditionProcedure {

	public static boolean executeProcedure(Map<String, Object> dependencies) {
		if (dependencies.get("world") == null) {
			if (!dependencies.containsKey("world"))
				HemMod.LOGGER.warn("Failed to load dependency world for procedure FluorescentLeavesParticlesAdditionalParticleExpiryCondition!");
			return false;
		}
		if (dependencies.get("x") == null) {
			if (!dependencies.containsKey("x"))
				HemMod.LOGGER.warn("Failed to load dependency x for procedure FluorescentLeavesParticlesAdditionalParticleExpiryCondition!");
			return false;
		}
		if (dependencies.get("y") == null) {
			if (!dependencies.containsKey("y"))
				HemMod.LOGGER.warn("Failed to load dependency y for procedure FluorescentLeavesParticlesAdditionalParticleExpiryCondition!");
			return false;
		}
		if (dependencies.get("z") == null) {
			if (!dependencies.containsKey("z"))
				HemMod.LOGGER.warn("Failed to load dependency z for procedure FluorescentLeavesParticlesAdditionalParticleExpiryCondition!");
			return false;
		}
		if (dependencies.get("onGround") == null) {
			if (!dependencies.containsKey("onGround"))
				HemMod.LOGGER.warn("Failed to load dependency onGround for procedure FluorescentLeavesParticlesAdditionalParticleExpiryCondition!");
			return false;
		}
		IWorld world = (IWorld) dependencies.get("world");
		double x = dependencies.get("x") instanceof Integer ? (int) dependencies.get("x") : (double) dependencies.get("x");
		double y = dependencies.get("y") instanceof Integer ? (int) dependencies.get("y") : (double) dependencies.get("y");
		double z = dependencies.get("z") instanceof Integer ? (int) dependencies.get("z") : (double) dependencies.get("z");
		boolean onGround = (boolean) dependencies.get("onGround");
		if (onGround) {
			if (Math.random() > 0.7) {
				if (BlockTags.getCollection().getTagByID(new ResourceLocation("forge:solid_block"))
						.contains((world.getBlockState(new BlockPos(x, y - 1, z))).getBlock())
						&& (world.getBlockState(new BlockPos(x, y, z))).getBlock() == Blocks.AIR) {
					world.setBlockState(new BlockPos(x, y, z), FallenLeavesBlock.block.getDefaultState(), 3);
				}
			}
			return true;
		}
		return false;
	}
}
