
package studio.halbear.hem.itemgroup;

import studio.halbear.hem.item.HotAirBalloonItemItem;
import studio.halbear.hem.HemModElements;

import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.item.ItemStack;
import net.minecraft.item.ItemGroup;

@HemModElements.ModElement.Tag
public class HalsExplorationModTechItemGroup extends HemModElements.ModElement {
	public HalsExplorationModTechItemGroup(HemModElements instance) {
		super(instance, 290);
	}

	@Override
	public void initElements() {
		tab = new ItemGroup("tabhals_exploration_mod_tech") {
			@OnlyIn(Dist.CLIENT)
			@Override
			public ItemStack createIcon() {
				return new ItemStack(HotAirBalloonItemItem.block);
			}

			@OnlyIn(Dist.CLIENT)
			public boolean hasSearchBar() {
				return false;
			}
		};
	}

	public static ItemGroup tab;
}
