
package studio.halbear.hem.entity.renderer;

import studio.halbear.hem.entity.HotAirBalloonEntity;

import net.minecraftforge.fml.client.registry.RenderingRegistry;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.entity.Entity;
import net.minecraft.client.renderer.model.ModelRenderer;
import net.minecraft.client.renderer.entity.model.EntityModel;
import net.minecraft.client.renderer.entity.MobRenderer;

import com.mojang.blaze3d.vertex.IVertexBuilder;
import com.mojang.blaze3d.matrix.MatrixStack;

@OnlyIn(Dist.CLIENT)
public class HotAirBalloonRenderer {
	public static class ModelRegisterHandler {
		@SubscribeEvent
		@OnlyIn(Dist.CLIENT)
		public void registerModels(ModelRegistryEvent event) {
			RenderingRegistry.registerEntityRenderingHandler(HotAirBalloonEntity.entity, renderManager -> {
				return new MobRenderer(renderManager, new ModelHotAirBalloon(), 0.5f) {

					@Override
					public ResourceLocation getEntityTexture(Entity entity) {
						return new ResourceLocation("hem:textures/entities/hotairballoon.png");
					}
				};
			});
		}
	}

	// Made with Blockbench 5.0.3
	// Exported for Minecraft version 1.15 - 1.16 with MCP mappings
	// Paste this class into your mod and generate all required imports
	public static class ModelHotAirBalloon extends EntityModel<Entity> {
		private final ModelRenderer Balloonstrip;
		private final ModelRenderer cube_r1;
		private final ModelRenderer cube_r2;
		private final ModelRenderer bone8;
		private final ModelRenderer cube_r3;
		private final ModelRenderer cube_r4;
		private final ModelRenderer bone16;
		private final ModelRenderer cube_r5;
		private final ModelRenderer cube_r6;
		private final ModelRenderer bone18;
		private final ModelRenderer cube_r7;
		private final ModelRenderer cube_r8;
		private final ModelRenderer cube_r9;
		private final ModelRenderer cube_r10;
		private final ModelRenderer cube_r11;
		private final ModelRenderer Balloonstrip11;
		private final ModelRenderer cube_r12;
		private final ModelRenderer cube_r13;
		private final ModelRenderer bone45;
		private final ModelRenderer cube_r14;
		private final ModelRenderer cube_r15;
		private final ModelRenderer bone46;
		private final ModelRenderer cube_r16;
		private final ModelRenderer cube_r17;
		private final ModelRenderer bone47;
		private final ModelRenderer cube_r18;
		private final ModelRenderer cube_r19;
		private final ModelRenderer cube_r20;
		private final ModelRenderer cube_r21;
		private final ModelRenderer cube_r22;
		private final ModelRenderer Balloonstrip12;
		private final ModelRenderer cube_r23;
		private final ModelRenderer cube_r24;
		private final ModelRenderer bone48;
		private final ModelRenderer cube_r25;
		private final ModelRenderer cube_r26;
		private final ModelRenderer bone49;
		private final ModelRenderer cube_r27;
		private final ModelRenderer cube_r28;
		private final ModelRenderer bone50;
		private final ModelRenderer cube_r29;
		private final ModelRenderer cube_r30;
		private final ModelRenderer cube_r31;
		private final ModelRenderer cube_r32;
		private final ModelRenderer cube_r33;
		private final ModelRenderer Balloonstrip10;
		private final ModelRenderer cube_r34;
		private final ModelRenderer cube_r35;
		private final ModelRenderer bone42;
		private final ModelRenderer cube_r36;
		private final ModelRenderer cube_r37;
		private final ModelRenderer bone43;
		private final ModelRenderer cube_r38;
		private final ModelRenderer cube_r39;
		private final ModelRenderer bone44;
		private final ModelRenderer cube_r40;
		private final ModelRenderer cube_r41;
		private final ModelRenderer cube_r42;
		private final ModelRenderer cube_r43;
		private final ModelRenderer cube_r44;
		private final ModelRenderer Balloonstrip2;
		private final ModelRenderer cube_r45;
		private final ModelRenderer cube_r46;
		private final ModelRenderer bone2;
		private final ModelRenderer cube_r47;
		private final ModelRenderer cube_r48;
		private final ModelRenderer bone27;
		private final ModelRenderer cube_r49;
		private final ModelRenderer cube_r50;
		private final ModelRenderer bone28;
		private final ModelRenderer cube_r51;
		private final ModelRenderer cube_r52;
		private final ModelRenderer cube_r53;
		private final ModelRenderer cube_r54;
		private final ModelRenderer cube_r55;
		private final ModelRenderer Balloonstrip9;
		private final ModelRenderer cube_r56;
		private final ModelRenderer cube_r57;
		private final ModelRenderer bone39;
		private final ModelRenderer cube_r58;
		private final ModelRenderer cube_r59;
		private final ModelRenderer bone40;
		private final ModelRenderer cube_r60;
		private final ModelRenderer cube_r61;
		private final ModelRenderer bone41;
		private final ModelRenderer cube_r62;
		private final ModelRenderer cube_r63;
		private final ModelRenderer cube_r64;
		private final ModelRenderer cube_r65;
		private final ModelRenderer cube_r66;
		private final ModelRenderer Balloonstrip7;
		private final ModelRenderer cube_r67;
		private final ModelRenderer cube_r68;
		private final ModelRenderer bone30;
		private final ModelRenderer cube_r69;
		private final ModelRenderer cube_r70;
		private final ModelRenderer bone31;
		private final ModelRenderer cube_r71;
		private final ModelRenderer cube_r72;
		private final ModelRenderer bone35;
		private final ModelRenderer cube_r73;
		private final ModelRenderer cube_r74;
		private final ModelRenderer cube_r75;
		private final ModelRenderer cube_r76;
		private final ModelRenderer cube_r77;
		private final ModelRenderer Balloonstrip8;
		private final ModelRenderer cube_r78;
		private final ModelRenderer cube_r79;
		private final ModelRenderer bone36;
		private final ModelRenderer cube_r80;
		private final ModelRenderer cube_r81;
		private final ModelRenderer bone37;
		private final ModelRenderer cube_r82;
		private final ModelRenderer cube_r83;
		private final ModelRenderer bone38;
		private final ModelRenderer cube_r84;
		private final ModelRenderer cube_r85;
		private final ModelRenderer cube_r86;
		private final ModelRenderer cube_r87;
		private final ModelRenderer cube_r88;
		private final ModelRenderer Engine;
		private final ModelRenderer bone34;
		private final ModelRenderer cube_r89;
		private final ModelRenderer bone32;
		private final ModelRenderer cube_r90;
		private final ModelRenderer cube_r91;
		private final ModelRenderer bone33;
		private final ModelRenderer cube_r92;
		private final ModelRenderer cube_r93;
		private final ModelRenderer bone60;
		private final ModelRenderer cube_r94;
		private final ModelRenderer bone61;
		private final ModelRenderer cube_r95;
		private final ModelRenderer cube_r96;
		private final ModelRenderer bone62;
		private final ModelRenderer cube_r97;
		private final ModelRenderer cube_r98;
		private final ModelRenderer bone;
		private final ModelRenderer cube_r99;
		private final ModelRenderer cube_r100;
		private final ModelRenderer cube_r101;
		private final ModelRenderer bone29;
		private final ModelRenderer cube_r102;
		private final ModelRenderer cube_r103;
		private final ModelRenderer bone25;
		private final ModelRenderer cube_r104;
		private final ModelRenderer cube_r105;
		private final ModelRenderer bone51;
		private final ModelRenderer cube_r106;
		private final ModelRenderer cube_r107;
		private final ModelRenderer cube_r108;
		private final ModelRenderer bone52;
		private final ModelRenderer cube_r109;
		private final ModelRenderer cube_r110;
		private final ModelRenderer bone53;
		private final ModelRenderer cube_r111;
		private final ModelRenderer cube_r112;
		private final ModelRenderer bone54;
		private final ModelRenderer cube_r113;
		private final ModelRenderer cube_r114;
		private final ModelRenderer cube_r115;
		private final ModelRenderer bone55;
		private final ModelRenderer cube_r116;
		private final ModelRenderer cube_r117;
		private final ModelRenderer bone56;
		private final ModelRenderer cube_r118;
		private final ModelRenderer cube_r119;
		private final ModelRenderer bone57;
		private final ModelRenderer cube_r120;
		private final ModelRenderer cube_r121;
		private final ModelRenderer cube_r122;
		private final ModelRenderer bone58;
		private final ModelRenderer cube_r123;
		private final ModelRenderer cube_r124;
		private final ModelRenderer bone59;
		private final ModelRenderer cube_r125;
		private final ModelRenderer cube_r126;
		private final ModelRenderer bone26;
		private final ModelRenderer cube_r127;
		private final ModelRenderer cube_r128;
		private final ModelRenderer bb_main;

		public ModelHotAirBalloon() {
			textureWidth = 256;
			textureHeight = 256;
			Balloonstrip = new ModelRenderer(this);
			Balloonstrip.setRotationPoint(0.0F, -91.4305F, 0.0F);
			cube_r1 = new ModelRenderer(this);
			cube_r1.setRotationPoint(0.0F, -0.5695F, 0.0F);
			Balloonstrip.addChild(cube_r1);
			setRotationAngle(cube_r1, 0.0F, 0.7854F, 0.0F);
			cube_r1.setTextureOffset(143, 98).addBox(-3.5F, -9.0F, -8.5F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r1.setTextureOffset(143, 95).addBox(-3.5F, 65.0F, -9.0F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r2 = new ModelRenderer(this);
			cube_r2.setRotationPoint(0.0F, 32.4305F, 0.0F);
			Balloonstrip.addChild(cube_r2);
			setRotationAngle(cube_r2, 0.0F, -0.7854F, 0.0F);
			cube_r2.setTextureOffset(53, 65).addBox(-26.75F, -19.0F, -11.0F, 0.0F, 20.0F, 22.0F, 0.0F, false);
			bone8 = new ModelRenderer(this);
			bone8.setRotationPoint(0.0F, 0.0F, 0.0F);
			Balloonstrip.addChild(bone8);
			setRotationAngle(bone8, 0.0F, 0.7854F, 0.0F);
			cube_r3 = new ModelRenderer(this);
			cube_r3.setRotationPoint(0.0F, 13.4305F, -27.0F);
			bone8.addChild(cube_r3);
			setRotationAngle(cube_r3, -1.5708F, -1.1345F, 1.5708F);
			cube_r3.setTextureOffset(98, 65).addBox(0.25F, -18.0F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r4 = new ModelRenderer(this);
			cube_r4.setRotationPoint(0.0F, -2.757F, -19.1661F);
			bone8.addChild(cube_r4);
			setRotationAngle(cube_r4, -1.5708F, -0.5236F, 1.5708F);
			cube_r4.setTextureOffset(0, 131).addBox(-0.0087F, -13.0183F, -8.0F, 0.0F, 13.0F, 16.0F, 0.0F, false);
			bone16 = new ModelRenderer(this);
			bone16.setRotationPoint(0.0F, 56.2431F, 0.0F);
			Balloonstrip.addChild(bone16);
			setRotationAngle(bone16, 0.0F, 0.7854F, 0.0F);
			cube_r5 = new ModelRenderer(this);
			cube_r5.setRotationPoint(0.0F, -16.8126F, -27.0F);
			bone16.addChild(cube_r5);
			setRotationAngle(cube_r5, 1.5708F, -1.2217F, -1.5708F);
			cube_r5.setTextureOffset(0, 66).addBox(2.3021F, -5.6382F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r6 = new ModelRenderer(this);
			cube_r6.setRotationPoint(0.0F, 0.0F, -20.6161F);
			bone16.addChild(cube_r6);
			setRotationAngle(cube_r6, 1.5708F, -0.8727F, -1.5708F);
			cube_r6.setTextureOffset(47, 108).addBox(3.848F, -4.5779F, -8.0F, 0.0F, 19.0F, 16.0F, 0.0F, false);
			bone18 = new ModelRenderer(this);
			bone18.setRotationPoint(0.0F, 1.9065F, 0.0F);
			Balloonstrip.addChild(bone18);
			setRotationAngle(bone18, 0.0F, 0.7854F, 0.0F);
			cube_r7 = new ModelRenderer(this);
			cube_r7.setRotationPoint(-3.5F, 68.0241F, -8.5F);
			bone18.addChild(cube_r7);
			setRotationAngle(cube_r7, 0.7148F, 0.4053F, 0.0127F);
			cube_r7.setTextureOffset(45, 66).addBox(-0.5584F, -24.2922F, 2.7582F, 1.0F, 21.0F, 1.0F, 0.0F, false);
			cube_r8 = new ModelRenderer(this);
			cube_r8.setRotationPoint(-8.7131F, 52.8042F, -21.201F);
			bone18.addChild(cube_r8);
			setRotationAngle(cube_r8, 0.3622F, 0.4084F, 0.0038F);
			cube_r8.setTextureOffset(33, 131).addBox(-0.5577F, -22.6869F, 1.7572F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r9 = new ModelRenderer(this);
			cube_r9.setRotationPoint(-11.1221F, 35.9524F, -27.0955F);
			bone18.addChild(cube_r9);
			setRotationAngle(cube_r9, 0.0F, 0.4084F, 0.0038F);
			cube_r9.setTextureOffset(89, 0).addBox(-0.6286F, -24.9941F, -0.0064F, 1.0F, 20.0F, 1.0F, 0.0F, false);
			cube_r10 = new ModelRenderer(this);
			cube_r10.setRotationPoint(-11.1221F, 15.9524F, -27.0955F);
			bone18.addChild(cube_r10);
			setRotationAngle(cube_r10, -0.48F, 0.4084F, 0.0038F);
			cube_r10.setTextureOffset(94, 0).addBox(-0.6286F, -22.4256F, -2.3143F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r11 = new ModelRenderer(this);
			cube_r11.setRotationPoint(-7.7729F, 0.0F, -19.4636F);
			bone18.addChild(cube_r11);
			setRotationAngle(cube_r11, -1.0997F, 0.3705F, -0.0196F);
			cube_r11.setTextureOffset(143, 64).addBox(-0.5062F, -16.2961F, -4.4365F, 1.0F, 14.0F, 1.0F, 0.0F, false);
			Balloonstrip11 = new ModelRenderer(this);
			Balloonstrip11.setRotationPoint(0.0F, -91.4305F, 0.0F);
			setRotationAngle(Balloonstrip11, 0.0F, 1.5708F, 0.0F);
			cube_r12 = new ModelRenderer(this);
			cube_r12.setRotationPoint(0.0F, -0.5695F, 0.0F);
			Balloonstrip11.addChild(cube_r12);
			setRotationAngle(cube_r12, 0.0F, 0.7854F, 0.0F);
			cube_r12.setTextureOffset(143, 98).addBox(-3.5F, -9.0F, -8.5F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r12.setTextureOffset(80, 129).addBox(-3.5F, 65.0F, -9.0F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r13 = new ModelRenderer(this);
			cube_r13.setRotationPoint(0.0F, 32.4305F, 0.0F);
			Balloonstrip11.addChild(cube_r13);
			setRotationAngle(cube_r13, 0.0F, -0.7854F, 0.0F);
			cube_r13.setTextureOffset(53, 65).addBox(-26.75F, -19.0F, -11.0F, 0.0F, 20.0F, 22.0F, 0.0F, false);
			bone45 = new ModelRenderer(this);
			bone45.setRotationPoint(0.0F, 0.0F, 0.0F);
			Balloonstrip11.addChild(bone45);
			setRotationAngle(bone45, 0.0F, 0.7854F, 0.0F);
			cube_r14 = new ModelRenderer(this);
			cube_r14.setRotationPoint(0.0F, 13.4305F, -27.0F);
			bone45.addChild(cube_r14);
			setRotationAngle(cube_r14, -1.5708F, -1.1345F, 1.5708F);
			cube_r14.setTextureOffset(98, 65).addBox(0.25F, -18.0F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r15 = new ModelRenderer(this);
			cube_r15.setRotationPoint(0.0F, -2.757F, -19.1661F);
			bone45.addChild(cube_r15);
			setRotationAngle(cube_r15, -1.5708F, -0.5236F, 1.5708F);
			cube_r15.setTextureOffset(0, 131).addBox(-0.0087F, -13.0183F, -8.0F, 0.0F, 13.0F, 16.0F, 0.0F, false);
			bone46 = new ModelRenderer(this);
			bone46.setRotationPoint(0.0F, 56.2431F, 0.0F);
			Balloonstrip11.addChild(bone46);
			setRotationAngle(bone46, 0.0F, 0.7854F, 0.0F);
			cube_r16 = new ModelRenderer(this);
			cube_r16.setRotationPoint(0.0F, -16.8126F, -27.0F);
			bone46.addChild(cube_r16);
			setRotationAngle(cube_r16, 1.5708F, -1.2217F, -1.5708F);
			cube_r16.setTextureOffset(0, 66).addBox(2.3021F, -5.6382F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r17 = new ModelRenderer(this);
			cube_r17.setRotationPoint(0.0F, 0.0F, -20.6161F);
			bone46.addChild(cube_r17);
			setRotationAngle(cube_r17, 1.5708F, -0.8727F, -1.5708F);
			cube_r17.setTextureOffset(47, 108).addBox(3.848F, -4.5779F, -8.0F, 0.0F, 19.0F, 16.0F, 0.0F, false);
			bone47 = new ModelRenderer(this);
			bone47.setRotationPoint(0.0F, 1.9065F, 0.0F);
			Balloonstrip11.addChild(bone47);
			setRotationAngle(bone47, 0.0F, 0.7854F, 0.0F);
			cube_r18 = new ModelRenderer(this);
			cube_r18.setRotationPoint(-3.5F, 68.0241F, -8.5F);
			bone47.addChild(cube_r18);
			setRotationAngle(cube_r18, 0.7148F, 0.4053F, 0.0127F);
			cube_r18.setTextureOffset(45, 66).addBox(-0.5584F, -24.2922F, 2.7582F, 1.0F, 21.0F, 1.0F, 0.0F, false);
			cube_r19 = new ModelRenderer(this);
			cube_r19.setRotationPoint(-8.7131F, 52.8042F, -21.201F);
			bone47.addChild(cube_r19);
			setRotationAngle(cube_r19, 0.3622F, 0.4084F, 0.0038F);
			cube_r19.setTextureOffset(33, 131).addBox(-0.5577F, -22.6869F, 1.7572F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r20 = new ModelRenderer(this);
			cube_r20.setRotationPoint(-11.1221F, 35.9524F, -27.0955F);
			bone47.addChild(cube_r20);
			setRotationAngle(cube_r20, 0.0F, 0.4084F, 0.0038F);
			cube_r20.setTextureOffset(89, 0).addBox(-0.6286F, -24.9941F, -0.0064F, 1.0F, 20.0F, 1.0F, 0.0F, false);
			cube_r21 = new ModelRenderer(this);
			cube_r21.setRotationPoint(-11.1221F, 15.9524F, -27.0955F);
			bone47.addChild(cube_r21);
			setRotationAngle(cube_r21, -0.48F, 0.4084F, 0.0038F);
			cube_r21.setTextureOffset(94, 0).addBox(-0.6286F, -22.4256F, -2.3143F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r22 = new ModelRenderer(this);
			cube_r22.setRotationPoint(-7.7729F, 0.0F, -19.4636F);
			bone47.addChild(cube_r22);
			setRotationAngle(cube_r22, -1.0997F, 0.3705F, -0.0196F);
			cube_r22.setTextureOffset(143, 64).addBox(-0.5062F, -16.2961F, -4.4365F, 1.0F, 14.0F, 1.0F, 0.0F, false);
			Balloonstrip12 = new ModelRenderer(this);
			Balloonstrip12.setRotationPoint(0.0F, -91.4305F, 0.0F);
			setRotationAngle(Balloonstrip12, 0.0F, 0.7854F, 0.0F);
			cube_r23 = new ModelRenderer(this);
			cube_r23.setRotationPoint(0.0F, -0.5695F, 0.0F);
			Balloonstrip12.addChild(cube_r23);
			setRotationAngle(cube_r23, 0.0F, 0.7854F, 0.0F);
			cube_r23.setTextureOffset(143, 98).addBox(-3.5F, -9.0F, -8.5F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r23.setTextureOffset(80, 129).addBox(-3.5F, 65.0F, -9.0F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r24 = new ModelRenderer(this);
			cube_r24.setRotationPoint(0.0F, 32.4305F, 0.0F);
			Balloonstrip12.addChild(cube_r24);
			setRotationAngle(cube_r24, 0.0F, -0.7854F, 0.0F);
			cube_r24.setTextureOffset(53, 65).addBox(-26.75F, -19.0F, -11.0F, 0.0F, 20.0F, 22.0F, 0.0F, false);
			bone48 = new ModelRenderer(this);
			bone48.setRotationPoint(0.0F, 0.0F, 0.0F);
			Balloonstrip12.addChild(bone48);
			setRotationAngle(bone48, 0.0F, 0.7854F, 0.0F);
			cube_r25 = new ModelRenderer(this);
			cube_r25.setRotationPoint(0.0F, 13.4305F, -27.0F);
			bone48.addChild(cube_r25);
			setRotationAngle(cube_r25, -1.5708F, -1.1345F, 1.5708F);
			cube_r25.setTextureOffset(98, 65).addBox(0.25F, -18.0F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r26 = new ModelRenderer(this);
			cube_r26.setRotationPoint(0.0F, -2.757F, -19.1661F);
			bone48.addChild(cube_r26);
			setRotationAngle(cube_r26, -1.5708F, -0.5236F, 1.5708F);
			cube_r26.setTextureOffset(0, 131).addBox(-0.0087F, -13.0183F, -8.0F, 0.0F, 13.0F, 16.0F, 0.0F, false);
			bone49 = new ModelRenderer(this);
			bone49.setRotationPoint(0.0F, 56.2431F, 0.0F);
			Balloonstrip12.addChild(bone49);
			setRotationAngle(bone49, 0.0F, 0.7854F, 0.0F);
			cube_r27 = new ModelRenderer(this);
			cube_r27.setRotationPoint(0.0F, -16.8126F, -27.0F);
			bone49.addChild(cube_r27);
			setRotationAngle(cube_r27, 1.5708F, -1.2217F, -1.5708F);
			cube_r27.setTextureOffset(0, 66).addBox(2.3021F, -5.6382F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r28 = new ModelRenderer(this);
			cube_r28.setRotationPoint(0.0F, 0.0F, -20.6161F);
			bone49.addChild(cube_r28);
			setRotationAngle(cube_r28, 1.5708F, -0.8727F, -1.5708F);
			cube_r28.setTextureOffset(47, 108).addBox(3.848F, -4.5779F, -8.0F, 0.0F, 19.0F, 16.0F, 0.0F, false);
			bone50 = new ModelRenderer(this);
			bone50.setRotationPoint(0.0F, 1.9065F, 0.0F);
			Balloonstrip12.addChild(bone50);
			setRotationAngle(bone50, 0.0F, 0.7854F, 0.0F);
			cube_r29 = new ModelRenderer(this);
			cube_r29.setRotationPoint(-3.5F, 68.0241F, -8.5F);
			bone50.addChild(cube_r29);
			setRotationAngle(cube_r29, 0.7148F, 0.4053F, 0.0127F);
			cube_r29.setTextureOffset(45, 66).addBox(-0.5584F, -24.2922F, 2.7582F, 1.0F, 21.0F, 1.0F, 0.0F, false);
			cube_r30 = new ModelRenderer(this);
			cube_r30.setRotationPoint(-8.7131F, 52.8042F, -21.201F);
			bone50.addChild(cube_r30);
			setRotationAngle(cube_r30, 0.3622F, 0.4084F, 0.0038F);
			cube_r30.setTextureOffset(33, 131).addBox(-0.5577F, -22.6869F, 1.7572F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r31 = new ModelRenderer(this);
			cube_r31.setRotationPoint(-11.1221F, 35.9524F, -27.0955F);
			bone50.addChild(cube_r31);
			setRotationAngle(cube_r31, 0.0F, 0.4084F, 0.0038F);
			cube_r31.setTextureOffset(89, 0).addBox(-0.6286F, -24.9941F, -0.0064F, 1.0F, 20.0F, 1.0F, 0.0F, false);
			cube_r32 = new ModelRenderer(this);
			cube_r32.setRotationPoint(-11.1221F, 15.9524F, -27.0955F);
			bone50.addChild(cube_r32);
			setRotationAngle(cube_r32, -0.48F, 0.4084F, 0.0038F);
			cube_r32.setTextureOffset(94, 0).addBox(-0.6286F, -22.4256F, -2.3143F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r33 = new ModelRenderer(this);
			cube_r33.setRotationPoint(-7.7729F, 0.0F, -19.4636F);
			bone50.addChild(cube_r33);
			setRotationAngle(cube_r33, -1.0997F, 0.3705F, -0.0196F);
			cube_r33.setTextureOffset(143, 64).addBox(-0.5062F, -16.2961F, -4.4365F, 1.0F, 14.0F, 1.0F, 0.0F, false);
			Balloonstrip10 = new ModelRenderer(this);
			Balloonstrip10.setRotationPoint(0.0F, -91.4305F, 0.0F);
			setRotationAngle(Balloonstrip10, 0.0F, -2.3562F, 0.0F);
			cube_r34 = new ModelRenderer(this);
			cube_r34.setRotationPoint(0.0F, -0.5695F, 0.0F);
			Balloonstrip10.addChild(cube_r34);
			setRotationAngle(cube_r34, 0.0F, 0.7854F, 0.0F);
			cube_r34.setTextureOffset(143, 98).addBox(-3.5F, -9.0F, -8.5F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r34.setTextureOffset(80, 129).addBox(-3.5F, 65.0F, -9.0F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r35 = new ModelRenderer(this);
			cube_r35.setRotationPoint(0.0F, 32.4305F, 0.0F);
			Balloonstrip10.addChild(cube_r35);
			setRotationAngle(cube_r35, 0.0F, -0.7854F, 0.0F);
			cube_r35.setTextureOffset(53, 65).addBox(-26.75F, -19.0F, -11.0F, 0.0F, 20.0F, 22.0F, 0.0F, false);
			bone42 = new ModelRenderer(this);
			bone42.setRotationPoint(0.0F, 0.0F, 0.0F);
			Balloonstrip10.addChild(bone42);
			setRotationAngle(bone42, 0.0F, 0.7854F, 0.0F);
			cube_r36 = new ModelRenderer(this);
			cube_r36.setRotationPoint(0.0F, 13.4305F, -27.0F);
			bone42.addChild(cube_r36);
			setRotationAngle(cube_r36, -1.5708F, -1.1345F, 1.5708F);
			cube_r36.setTextureOffset(98, 65).addBox(0.25F, -18.0F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r37 = new ModelRenderer(this);
			cube_r37.setRotationPoint(0.0F, -2.757F, -19.1661F);
			bone42.addChild(cube_r37);
			setRotationAngle(cube_r37, -1.5708F, -0.5236F, 1.5708F);
			cube_r37.setTextureOffset(0, 131).addBox(-0.0087F, -13.0183F, -8.0F, 0.0F, 13.0F, 16.0F, 0.0F, false);
			bone43 = new ModelRenderer(this);
			bone43.setRotationPoint(0.0F, 56.2431F, 0.0F);
			Balloonstrip10.addChild(bone43);
			setRotationAngle(bone43, 0.0F, 0.7854F, 0.0F);
			cube_r38 = new ModelRenderer(this);
			cube_r38.setRotationPoint(0.0F, -16.8126F, -27.0F);
			bone43.addChild(cube_r38);
			setRotationAngle(cube_r38, 1.5708F, -1.2217F, -1.5708F);
			cube_r38.setTextureOffset(0, 66).addBox(2.3021F, -5.6382F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r39 = new ModelRenderer(this);
			cube_r39.setRotationPoint(0.0F, 0.0F, -20.6161F);
			bone43.addChild(cube_r39);
			setRotationAngle(cube_r39, 1.5708F, -0.8727F, -1.5708F);
			cube_r39.setTextureOffset(47, 108).addBox(3.848F, -4.5779F, -8.0F, 0.0F, 19.0F, 16.0F, 0.0F, false);
			bone44 = new ModelRenderer(this);
			bone44.setRotationPoint(0.0F, 1.9065F, 0.0F);
			Balloonstrip10.addChild(bone44);
			setRotationAngle(bone44, 0.0F, 0.7854F, 0.0F);
			cube_r40 = new ModelRenderer(this);
			cube_r40.setRotationPoint(-3.5F, 68.0241F, -8.5F);
			bone44.addChild(cube_r40);
			setRotationAngle(cube_r40, 0.7148F, 0.4053F, 0.0127F);
			cube_r40.setTextureOffset(45, 66).addBox(-0.5584F, -24.2922F, 2.7582F, 1.0F, 21.0F, 1.0F, 0.0F, false);
			cube_r41 = new ModelRenderer(this);
			cube_r41.setRotationPoint(-8.7131F, 52.8042F, -21.201F);
			bone44.addChild(cube_r41);
			setRotationAngle(cube_r41, 0.3622F, 0.4084F, 0.0038F);
			cube_r41.setTextureOffset(33, 131).addBox(-0.5577F, -22.6869F, 1.7572F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r42 = new ModelRenderer(this);
			cube_r42.setRotationPoint(-11.1221F, 35.9524F, -27.0955F);
			bone44.addChild(cube_r42);
			setRotationAngle(cube_r42, 0.0F, 0.4084F, 0.0038F);
			cube_r42.setTextureOffset(89, 0).addBox(-0.6286F, -24.9941F, -0.0064F, 1.0F, 20.0F, 1.0F, 0.0F, false);
			cube_r43 = new ModelRenderer(this);
			cube_r43.setRotationPoint(-11.1221F, 15.9524F, -27.0955F);
			bone44.addChild(cube_r43);
			setRotationAngle(cube_r43, -0.48F, 0.4084F, 0.0038F);
			cube_r43.setTextureOffset(94, 0).addBox(-0.6286F, -22.4256F, -2.3143F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r44 = new ModelRenderer(this);
			cube_r44.setRotationPoint(-7.7729F, 0.0F, -19.4636F);
			bone44.addChild(cube_r44);
			setRotationAngle(cube_r44, -1.0997F, 0.3705F, -0.0196F);
			cube_r44.setTextureOffset(143, 64).addBox(-0.5062F, -16.2961F, -4.4365F, 1.0F, 14.0F, 1.0F, 0.0F, false);
			Balloonstrip2 = new ModelRenderer(this);
			Balloonstrip2.setRotationPoint(0.0F, -91.4305F, 0.0F);
			setRotationAngle(Balloonstrip2, 0.0F, -0.7854F, 0.0F);
			cube_r45 = new ModelRenderer(this);
			cube_r45.setRotationPoint(0.0F, -0.5695F, 0.0F);
			Balloonstrip2.addChild(cube_r45);
			setRotationAngle(cube_r45, 0.0F, 0.7854F, 0.0F);
			cube_r45.setTextureOffset(143, 98).addBox(-3.5F, -9.0F, -8.5F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r45.setTextureOffset(80, 129).addBox(-3.5F, 65.0F, -9.0F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r46 = new ModelRenderer(this);
			cube_r46.setRotationPoint(0.0F, 32.4305F, 0.0F);
			Balloonstrip2.addChild(cube_r46);
			setRotationAngle(cube_r46, 0.0F, -0.7854F, 0.0F);
			cube_r46.setTextureOffset(53, 65).addBox(-26.75F, -19.0F, -11.0F, 0.0F, 20.0F, 22.0F, 0.0F, false);
			bone2 = new ModelRenderer(this);
			bone2.setRotationPoint(0.0F, 0.0F, 0.0F);
			Balloonstrip2.addChild(bone2);
			setRotationAngle(bone2, 0.0F, 0.7854F, 0.0F);
			cube_r47 = new ModelRenderer(this);
			cube_r47.setRotationPoint(0.0F, 13.4305F, -27.0F);
			bone2.addChild(cube_r47);
			setRotationAngle(cube_r47, -1.5708F, -1.1345F, 1.5708F);
			cube_r47.setTextureOffset(98, 65).addBox(0.25F, -18.0F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r48 = new ModelRenderer(this);
			cube_r48.setRotationPoint(0.0F, -2.757F, -19.1661F);
			bone2.addChild(cube_r48);
			setRotationAngle(cube_r48, -1.5708F, -0.5236F, 1.5708F);
			cube_r48.setTextureOffset(0, 131).addBox(-0.0087F, -13.0183F, -8.0F, 0.0F, 13.0F, 16.0F, 0.0F, false);
			bone27 = new ModelRenderer(this);
			bone27.setRotationPoint(0.0F, 56.2431F, 0.0F);
			Balloonstrip2.addChild(bone27);
			setRotationAngle(bone27, 0.0F, 0.7854F, 0.0F);
			cube_r49 = new ModelRenderer(this);
			cube_r49.setRotationPoint(0.0F, -16.8126F, -27.0F);
			bone27.addChild(cube_r49);
			setRotationAngle(cube_r49, 1.5708F, -1.2217F, -1.5708F);
			cube_r49.setTextureOffset(0, 66).addBox(2.3021F, -5.6382F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r50 = new ModelRenderer(this);
			cube_r50.setRotationPoint(0.0F, 0.0F, -20.6161F);
			bone27.addChild(cube_r50);
			setRotationAngle(cube_r50, 1.5708F, -0.8727F, -1.5708F);
			cube_r50.setTextureOffset(47, 108).addBox(3.848F, -4.5779F, -8.0F, 0.0F, 19.0F, 16.0F, 0.0F, false);
			bone28 = new ModelRenderer(this);
			bone28.setRotationPoint(0.0F, 1.9065F, 0.0F);
			Balloonstrip2.addChild(bone28);
			setRotationAngle(bone28, 0.0F, 0.7854F, 0.0F);
			cube_r51 = new ModelRenderer(this);
			cube_r51.setRotationPoint(-3.5F, 68.0241F, -8.5F);
			bone28.addChild(cube_r51);
			setRotationAngle(cube_r51, 0.7148F, 0.4053F, 0.0127F);
			cube_r51.setTextureOffset(45, 66).addBox(-0.5584F, -24.2922F, 2.7582F, 1.0F, 21.0F, 1.0F, 0.0F, false);
			cube_r52 = new ModelRenderer(this);
			cube_r52.setRotationPoint(-8.7131F, 52.8042F, -21.201F);
			bone28.addChild(cube_r52);
			setRotationAngle(cube_r52, 0.3622F, 0.4084F, 0.0038F);
			cube_r52.setTextureOffset(33, 131).addBox(-0.5577F, -22.6869F, 1.7572F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r53 = new ModelRenderer(this);
			cube_r53.setRotationPoint(-11.1221F, 35.9524F, -27.0955F);
			bone28.addChild(cube_r53);
			setRotationAngle(cube_r53, 0.0F, 0.4084F, 0.0038F);
			cube_r53.setTextureOffset(89, 0).addBox(-0.6286F, -24.9941F, -0.0064F, 1.0F, 20.0F, 1.0F, 0.0F, false);
			cube_r54 = new ModelRenderer(this);
			cube_r54.setRotationPoint(-11.1221F, 15.9524F, -27.0955F);
			bone28.addChild(cube_r54);
			setRotationAngle(cube_r54, -0.48F, 0.4084F, 0.0038F);
			cube_r54.setTextureOffset(94, 0).addBox(-0.6286F, -22.4256F, -2.3143F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r55 = new ModelRenderer(this);
			cube_r55.setRotationPoint(-7.7729F, 0.0F, -19.4636F);
			bone28.addChild(cube_r55);
			setRotationAngle(cube_r55, -1.0997F, 0.3705F, -0.0196F);
			cube_r55.setTextureOffset(143, 64).addBox(-0.5062F, -16.2961F, -4.4365F, 1.0F, 14.0F, 1.0F, 0.0F, false);
			Balloonstrip9 = new ModelRenderer(this);
			Balloonstrip9.setRotationPoint(0.0F, -91.4305F, 0.0F);
			setRotationAngle(Balloonstrip9, 0.0F, 3.1416F, 0.0F);
			cube_r56 = new ModelRenderer(this);
			cube_r56.setRotationPoint(0.0F, -0.5695F, 0.0F);
			Balloonstrip9.addChild(cube_r56);
			setRotationAngle(cube_r56, 0.0F, 0.7854F, 0.0F);
			cube_r56.setTextureOffset(143, 98).addBox(-3.5F, -9.0F, -8.5F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r56.setTextureOffset(80, 129).addBox(-3.5F, 65.0F, -9.0F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r57 = new ModelRenderer(this);
			cube_r57.setRotationPoint(0.0F, 32.4305F, 0.0F);
			Balloonstrip9.addChild(cube_r57);
			setRotationAngle(cube_r57, 0.0F, -0.7854F, 0.0F);
			cube_r57.setTextureOffset(53, 65).addBox(-26.75F, -19.0F, -11.0F, 0.0F, 20.0F, 22.0F, 0.0F, false);
			bone39 = new ModelRenderer(this);
			bone39.setRotationPoint(0.0F, 0.0F, 0.0F);
			Balloonstrip9.addChild(bone39);
			setRotationAngle(bone39, 0.0F, 0.7854F, 0.0F);
			cube_r58 = new ModelRenderer(this);
			cube_r58.setRotationPoint(0.0F, 13.4305F, -27.0F);
			bone39.addChild(cube_r58);
			setRotationAngle(cube_r58, -1.5708F, -1.1345F, 1.5708F);
			cube_r58.setTextureOffset(98, 65).addBox(0.25F, -18.0F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r59 = new ModelRenderer(this);
			cube_r59.setRotationPoint(0.0F, -2.757F, -19.1661F);
			bone39.addChild(cube_r59);
			setRotationAngle(cube_r59, -1.5708F, -0.5236F, 1.5708F);
			cube_r59.setTextureOffset(0, 131).addBox(-0.0087F, -13.0183F, -8.0F, 0.0F, 13.0F, 16.0F, 0.0F, false);
			bone40 = new ModelRenderer(this);
			bone40.setRotationPoint(0.0F, 56.2431F, 0.0F);
			Balloonstrip9.addChild(bone40);
			setRotationAngle(bone40, 0.0F, 0.7854F, 0.0F);
			cube_r60 = new ModelRenderer(this);
			cube_r60.setRotationPoint(0.0F, -16.8126F, -27.0F);
			bone40.addChild(cube_r60);
			setRotationAngle(cube_r60, 1.5708F, -1.2217F, -1.5708F);
			cube_r60.setTextureOffset(0, 66).addBox(2.3021F, -5.6382F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r61 = new ModelRenderer(this);
			cube_r61.setRotationPoint(0.0F, 0.0F, -20.6161F);
			bone40.addChild(cube_r61);
			setRotationAngle(cube_r61, 1.5708F, -0.8727F, -1.5708F);
			cube_r61.setTextureOffset(47, 108).addBox(3.848F, -4.5779F, -8.0F, 0.0F, 19.0F, 16.0F, 0.0F, false);
			bone41 = new ModelRenderer(this);
			bone41.setRotationPoint(0.0F, 1.9065F, 0.0F);
			Balloonstrip9.addChild(bone41);
			setRotationAngle(bone41, 0.0F, 0.7854F, 0.0F);
			cube_r62 = new ModelRenderer(this);
			cube_r62.setRotationPoint(-3.5F, 68.0241F, -8.5F);
			bone41.addChild(cube_r62);
			setRotationAngle(cube_r62, 0.7148F, 0.4053F, 0.0127F);
			cube_r62.setTextureOffset(45, 66).addBox(-0.5584F, -24.2922F, 2.7582F, 1.0F, 21.0F, 1.0F, 0.0F, false);
			cube_r63 = new ModelRenderer(this);
			cube_r63.setRotationPoint(-8.7131F, 52.8042F, -21.201F);
			bone41.addChild(cube_r63);
			setRotationAngle(cube_r63, 0.3622F, 0.4084F, 0.0038F);
			cube_r63.setTextureOffset(33, 131).addBox(-0.5577F, -22.6869F, 1.7572F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r64 = new ModelRenderer(this);
			cube_r64.setRotationPoint(-11.1221F, 35.9524F, -27.0955F);
			bone41.addChild(cube_r64);
			setRotationAngle(cube_r64, 0.0F, 0.4084F, 0.0038F);
			cube_r64.setTextureOffset(89, 0).addBox(-0.6286F, -24.9941F, -0.0064F, 1.0F, 20.0F, 1.0F, 0.0F, false);
			cube_r65 = new ModelRenderer(this);
			cube_r65.setRotationPoint(-11.1221F, 15.9524F, -27.0955F);
			bone41.addChild(cube_r65);
			setRotationAngle(cube_r65, -0.48F, 0.4084F, 0.0038F);
			cube_r65.setTextureOffset(94, 0).addBox(-0.6286F, -22.4256F, -2.3143F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r66 = new ModelRenderer(this);
			cube_r66.setRotationPoint(-7.7729F, 0.0F, -19.4636F);
			bone41.addChild(cube_r66);
			setRotationAngle(cube_r66, -1.0997F, 0.3705F, -0.0196F);
			cube_r66.setTextureOffset(143, 64).addBox(-0.5062F, -16.2961F, -4.4365F, 1.0F, 14.0F, 1.0F, 0.0F, false);
			Balloonstrip7 = new ModelRenderer(this);
			Balloonstrip7.setRotationPoint(0.0F, -91.4305F, 0.0F);
			setRotationAngle(Balloonstrip7, 0.0F, -1.5708F, 0.0F);
			cube_r67 = new ModelRenderer(this);
			cube_r67.setRotationPoint(0.0F, -0.5695F, 0.0F);
			Balloonstrip7.addChild(cube_r67);
			setRotationAngle(cube_r67, 0.0F, 0.7854F, 0.0F);
			cube_r67.setTextureOffset(143, 98).addBox(-3.5F, -9.0F, -8.5F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r67.setTextureOffset(80, 129).addBox(-3.5F, 65.0F, -9.0F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r68 = new ModelRenderer(this);
			cube_r68.setRotationPoint(0.0F, 32.4305F, 0.0F);
			Balloonstrip7.addChild(cube_r68);
			setRotationAngle(cube_r68, 0.0F, -0.7854F, 0.0F);
			cube_r68.setTextureOffset(53, 65).addBox(-26.75F, -19.0F, -11.0F, 0.0F, 20.0F, 22.0F, 0.0F, false);
			bone30 = new ModelRenderer(this);
			bone30.setRotationPoint(0.0F, 0.0F, 0.0F);
			Balloonstrip7.addChild(bone30);
			setRotationAngle(bone30, 0.0F, 0.7854F, 0.0F);
			cube_r69 = new ModelRenderer(this);
			cube_r69.setRotationPoint(0.0F, 13.4305F, -27.0F);
			bone30.addChild(cube_r69);
			setRotationAngle(cube_r69, -1.5708F, -1.1345F, 1.5708F);
			cube_r69.setTextureOffset(98, 65).addBox(0.25F, -18.0F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r70 = new ModelRenderer(this);
			cube_r70.setRotationPoint(0.0F, -2.757F, -19.1661F);
			bone30.addChild(cube_r70);
			setRotationAngle(cube_r70, -1.5708F, -0.5236F, 1.5708F);
			cube_r70.setTextureOffset(0, 131).addBox(-0.0087F, -13.0183F, -8.0F, 0.0F, 13.0F, 16.0F, 0.0F, false);
			bone31 = new ModelRenderer(this);
			bone31.setRotationPoint(0.0F, 56.2431F, 0.0F);
			Balloonstrip7.addChild(bone31);
			setRotationAngle(bone31, 0.0F, 0.7854F, 0.0F);
			cube_r71 = new ModelRenderer(this);
			cube_r71.setRotationPoint(0.0F, -16.8126F, -27.0F);
			bone31.addChild(cube_r71);
			setRotationAngle(cube_r71, 1.5708F, -1.2217F, -1.5708F);
			cube_r71.setTextureOffset(0, 66).addBox(2.3021F, -5.6382F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r72 = new ModelRenderer(this);
			cube_r72.setRotationPoint(0.0F, 0.0F, -20.6161F);
			bone31.addChild(cube_r72);
			setRotationAngle(cube_r72, 1.5708F, -0.8727F, -1.5708F);
			cube_r72.setTextureOffset(47, 108).addBox(3.848F, -4.5779F, -8.0F, 0.0F, 19.0F, 16.0F, 0.0F, false);
			bone35 = new ModelRenderer(this);
			bone35.setRotationPoint(0.0F, 1.9065F, 0.0F);
			Balloonstrip7.addChild(bone35);
			setRotationAngle(bone35, 0.0F, 0.7854F, 0.0F);
			cube_r73 = new ModelRenderer(this);
			cube_r73.setRotationPoint(-3.5F, 68.0241F, -8.5F);
			bone35.addChild(cube_r73);
			setRotationAngle(cube_r73, 0.7148F, 0.4053F, 0.0127F);
			cube_r73.setTextureOffset(45, 66).addBox(-0.5584F, -24.2922F, 2.7582F, 1.0F, 21.0F, 1.0F, 0.0F, false);
			cube_r74 = new ModelRenderer(this);
			cube_r74.setRotationPoint(-8.7131F, 52.8042F, -21.201F);
			bone35.addChild(cube_r74);
			setRotationAngle(cube_r74, 0.3622F, 0.4084F, 0.0038F);
			cube_r74.setTextureOffset(33, 131).addBox(-0.5577F, -22.6869F, 1.7572F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r75 = new ModelRenderer(this);
			cube_r75.setRotationPoint(-11.1221F, 35.9524F, -27.0955F);
			bone35.addChild(cube_r75);
			setRotationAngle(cube_r75, 0.0F, 0.4084F, 0.0038F);
			cube_r75.setTextureOffset(89, 0).addBox(-0.6286F, -24.9941F, -0.0064F, 1.0F, 20.0F, 1.0F, 0.0F, false);
			cube_r76 = new ModelRenderer(this);
			cube_r76.setRotationPoint(-11.1221F, 15.9524F, -27.0955F);
			bone35.addChild(cube_r76);
			setRotationAngle(cube_r76, -0.48F, 0.4084F, 0.0038F);
			cube_r76.setTextureOffset(94, 0).addBox(-0.6286F, -22.4256F, -2.3143F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r77 = new ModelRenderer(this);
			cube_r77.setRotationPoint(-7.7729F, 0.0F, -19.4636F);
			bone35.addChild(cube_r77);
			setRotationAngle(cube_r77, -1.0997F, 0.3705F, -0.0196F);
			cube_r77.setTextureOffset(143, 64).addBox(-0.5062F, -16.2961F, -4.4365F, 1.0F, 14.0F, 1.0F, 0.0F, false);
			Balloonstrip8 = new ModelRenderer(this);
			Balloonstrip8.setRotationPoint(0.0F, -91.4305F, 0.0F);
			setRotationAngle(Balloonstrip8, 0.0F, 2.3562F, 0.0F);
			cube_r78 = new ModelRenderer(this);
			cube_r78.setRotationPoint(0.0F, -0.5695F, 0.0F);
			Balloonstrip8.addChild(cube_r78);
			setRotationAngle(cube_r78, 0.0F, 0.7854F, 0.0F);
			cube_r78.setTextureOffset(143, 98).addBox(-3.5F, -9.0F, -8.5F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r78.setTextureOffset(80, 129).addBox(-3.5F, 65.0F, -9.0F, 7.0F, 1.0F, 1.0F, 0.0F, false);
			cube_r79 = new ModelRenderer(this);
			cube_r79.setRotationPoint(0.0F, 32.4305F, 0.0F);
			Balloonstrip8.addChild(cube_r79);
			setRotationAngle(cube_r79, 0.0F, -0.7854F, 0.0F);
			cube_r79.setTextureOffset(53, 65).addBox(-26.75F, -19.0F, -11.0F, 0.0F, 20.0F, 22.0F, 0.0F, false);
			bone36 = new ModelRenderer(this);
			bone36.setRotationPoint(0.0F, 0.0F, 0.0F);
			Balloonstrip8.addChild(bone36);
			setRotationAngle(bone36, 0.0F, 0.7854F, 0.0F);
			cube_r80 = new ModelRenderer(this);
			cube_r80.setRotationPoint(0.0F, 13.4305F, -27.0F);
			bone36.addChild(cube_r80);
			setRotationAngle(cube_r80, -1.5708F, -1.1345F, 1.5708F);
			cube_r80.setTextureOffset(98, 65).addBox(0.25F, -18.0F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r81 = new ModelRenderer(this);
			cube_r81.setRotationPoint(0.0F, -2.757F, -19.1661F);
			bone36.addChild(cube_r81);
			setRotationAngle(cube_r81, -1.5708F, -0.5236F, 1.5708F);
			cube_r81.setTextureOffset(0, 131).addBox(-0.0087F, -13.0183F, -8.0F, 0.0F, 13.0F, 16.0F, 0.0F, false);
			bone37 = new ModelRenderer(this);
			bone37.setRotationPoint(0.0F, 56.2431F, 0.0F);
			Balloonstrip8.addChild(bone37);
			setRotationAngle(bone37, 0.0F, 0.7854F, 0.0F);
			cube_r82 = new ModelRenderer(this);
			cube_r82.setRotationPoint(0.0F, -16.8126F, -27.0F);
			bone37.addChild(cube_r82);
			setRotationAngle(cube_r82, 1.5708F, -1.2217F, -1.5708F);
			cube_r82.setTextureOffset(0, 66).addBox(2.3021F, -5.6382F, -11.0F, 0.0F, 18.0F, 22.0F, 0.0F, false);
			cube_r83 = new ModelRenderer(this);
			cube_r83.setRotationPoint(0.0F, 0.0F, -20.6161F);
			bone37.addChild(cube_r83);
			setRotationAngle(cube_r83, 1.5708F, -0.8727F, -1.5708F);
			cube_r83.setTextureOffset(47, 108).addBox(3.848F, -4.5779F, -8.0F, 0.0F, 19.0F, 16.0F, 0.0F, false);
			bone38 = new ModelRenderer(this);
			bone38.setRotationPoint(0.0F, 1.9065F, 0.0F);
			Balloonstrip8.addChild(bone38);
			setRotationAngle(bone38, 0.0F, 0.7854F, 0.0F);
			cube_r84 = new ModelRenderer(this);
			cube_r84.setRotationPoint(-3.5F, 68.0241F, -8.5F);
			bone38.addChild(cube_r84);
			setRotationAngle(cube_r84, 0.7148F, 0.4053F, 0.0127F);
			cube_r84.setTextureOffset(45, 66).addBox(-0.5584F, -24.2922F, 2.7582F, 1.0F, 21.0F, 1.0F, 0.0F, false);
			cube_r85 = new ModelRenderer(this);
			cube_r85.setRotationPoint(-8.7131F, 52.8042F, -21.201F);
			bone38.addChild(cube_r85);
			setRotationAngle(cube_r85, 0.3622F, 0.4084F, 0.0038F);
			cube_r85.setTextureOffset(33, 131).addBox(-0.5577F, -22.6869F, 1.7572F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r86 = new ModelRenderer(this);
			cube_r86.setRotationPoint(-11.1221F, 35.9524F, -27.0955F);
			bone38.addChild(cube_r86);
			setRotationAngle(cube_r86, 0.0F, 0.4084F, 0.0038F);
			cube_r86.setTextureOffset(89, 0).addBox(-0.6286F, -24.9941F, -0.0064F, 1.0F, 20.0F, 1.0F, 0.0F, false);
			cube_r87 = new ModelRenderer(this);
			cube_r87.setRotationPoint(-11.1221F, 15.9524F, -27.0955F);
			bone38.addChild(cube_r87);
			setRotationAngle(cube_r87, -0.48F, 0.4084F, 0.0038F);
			cube_r87.setTextureOffset(94, 0).addBox(-0.6286F, -22.4256F, -2.3143F, 1.0F, 18.0F, 1.0F, 0.0F, false);
			cube_r88 = new ModelRenderer(this);
			cube_r88.setRotationPoint(-7.7729F, 0.0F, -19.4636F);
			bone38.addChild(cube_r88);
			setRotationAngle(cube_r88, -1.0997F, 0.3705F, -0.0196F);
			cube_r88.setTextureOffset(143, 64).addBox(-0.5062F, -16.2961F, -4.4365F, 1.0F, 14.0F, 1.0F, 0.0F, false);
			Engine = new ModelRenderer(this);
			Engine.setRotationPoint(0.0F, -6.0F, 0.0F);
			Engine.setTextureOffset(38, 131).addBox(-2.0F, -3.0F, -2.0F, 0.0F, 8.0F, 4.0F, 0.0F, false);
			Engine.setTextureOffset(80, 108).addBox(-2.0F, -16.75F, -2.0F, 4.0F, 4.0F, 4.0F, 0.0F, false);
			Engine.setTextureOffset(80, 133).addBox(-3.0F, -13.0F, -3.0F, 6.0F, 10.0F, 6.0F, 0.0F, false);
			bone34 = new ModelRenderer(this);
			bone34.setRotationPoint(0.0667F, 17.5F, 0.0F);
			setRotationAngle(bone34, 0.0F, 1.5708F, 0.0F);
			cube_r89 = new ModelRenderer(this);
			cube_r89.setRotationPoint(0.3333F, 5.5F, 0.0F);
			bone34.addChild(cube_r89);
			setRotationAngle(cube_r89, 0.0F, 1.5708F, 0.0F);
			cube_r89.setTextureOffset(0, 24).addBox(13.0F, -15.0F, -13.0F, 0.0F, 15.0F, 26.0F, 0.0F, false);
			bone32 = new ModelRenderer(this);
			bone32.setRotationPoint(-3.1667F, 0.5F, -15.5F);
			bone34.addChild(bone32);
			setRotationAngle(bone32, -0.4305F, 0.0735F, 0.1585F);
			cube_r90 = new ModelRenderer(this);
			cube_r90.setRotationPoint(0.0F, -6.0F, 0.0F);
			bone32.addChild(cube_r90);
			setRotationAngle(cube_r90, 0.0F, 1.5708F, 0.0F);
			cube_r90.setTextureOffset(143, 101).addBox(-1.5F, 2.0F, -1.5F, 3.0F, 1.0F, 3.0F, 0.0F, false);
			cube_r90.setTextureOffset(105, 133).addBox(-2.5F, 3.0F, -2.5F, 5.0F, 5.0F, 5.0F, 0.0F, false);
			cube_r91 = new ModelRenderer(this);
			cube_r91.setRotationPoint(-0.5F, -7.0F, -0.5F);
			bone32.addChild(cube_r91);
			setRotationAngle(cube_r91, 0.0F, 1.5708F, 0.0F);
			cube_r91.setTextureOffset(80, 117).addBox(-2.5F, 2.0F, -1.5F, 4.0F, 1.0F, 4.0F, 0.0F, false);
			bone33 = new ModelRenderer(this);
			bone33.setRotationPoint(2.8333F, 1.5F, -15.5F);
			bone34.addChild(bone33);
			setRotationAngle(bone33, -0.4185F, -0.1274F, -0.2783F);
			cube_r92 = new ModelRenderer(this);
			cube_r92.setRotationPoint(0.0F, -6.0F, 0.0F);
			bone33.addChild(cube_r92);
			setRotationAngle(cube_r92, 0.0F, 1.5708F, 0.0F);
			cube_r92.setTextureOffset(43, 144).addBox(-1.5F, 2.0F, -1.5F, 3.0F, 1.0F, 3.0F, 0.0F, false);
			cube_r92.setTextureOffset(126, 133).addBox(-2.5F, 3.0F, -2.5F, 5.0F, 5.0F, 5.0F, 0.0F, false);
			cube_r93 = new ModelRenderer(this);
			cube_r93.setRotationPoint(-0.5F, -7.0F, -0.5F);
			bone33.addChild(cube_r93);
			setRotationAngle(cube_r93, 0.0F, 1.5708F, 0.0F);
			cube_r93.setTextureOffset(80, 123).addBox(-2.5F, 2.0F, -1.5F, 4.0F, 1.0F, 4.0F, 0.0F, false);
			bone60 = new ModelRenderer(this);
			bone60.setRotationPoint(-0.0667F, 17.5F, 0.0F);
			setRotationAngle(bone60, 0.0F, -1.5708F, 0.0F);
			cube_r94 = new ModelRenderer(this);
			cube_r94.setRotationPoint(-0.3333F, 5.5F, 0.0F);
			bone60.addChild(cube_r94);
			setRotationAngle(cube_r94, 0.0F, -1.5708F, 0.0F);
			cube_r94.setTextureOffset(0, 24).addBox(-13.0F, -15.0F, -13.0F, 0.0F, 15.0F, 26.0F, 0.0F, true);
			bone61 = new ModelRenderer(this);
			bone61.setRotationPoint(3.1667F, 0.5F, -15.5F);
			bone60.addChild(bone61);
			setRotationAngle(bone61, -0.4305F, -0.0735F, -0.1585F);
			cube_r95 = new ModelRenderer(this);
			cube_r95.setRotationPoint(0.0F, -6.0F, 0.0F);
			bone61.addChild(cube_r95);
			setRotationAngle(cube_r95, 0.0F, -1.5708F, 0.0F);
			cube_r95.setTextureOffset(143, 101).addBox(-1.5F, 2.0F, -1.5F, 3.0F, 1.0F, 3.0F, 0.0F, true);
			cube_r95.setTextureOffset(105, 133).addBox(-2.5F, 3.0F, -2.5F, 5.0F, 5.0F, 5.0F, 0.0F, true);
			cube_r96 = new ModelRenderer(this);
			cube_r96.setRotationPoint(0.5F, -7.0F, -0.5F);
			bone61.addChild(cube_r96);
			setRotationAngle(cube_r96, 0.0F, -1.5708F, 0.0F);
			cube_r96.setTextureOffset(80, 117).addBox(-1.5F, 2.0F, -1.5F, 4.0F, 1.0F, 4.0F, 0.0F, true);
			bone62 = new ModelRenderer(this);
			bone62.setRotationPoint(-2.8333F, 1.5F, -15.5F);
			bone60.addChild(bone62);
			setRotationAngle(bone62, -0.4185F, 0.1274F, 0.2783F);
			cube_r97 = new ModelRenderer(this);
			cube_r97.setRotationPoint(0.0F, -6.0F, 0.0F);
			bone62.addChild(cube_r97);
			setRotationAngle(cube_r97, 0.0F, -1.5708F, 0.0F);
			cube_r97.setTextureOffset(43, 144).addBox(-1.5F, 2.0F, -1.5F, 3.0F, 1.0F, 3.0F, 0.0F, true);
			cube_r97.setTextureOffset(126, 133).addBox(-2.5F, 3.0F, -2.5F, 5.0F, 5.0F, 5.0F, 0.0F, true);
			cube_r98 = new ModelRenderer(this);
			cube_r98.setRotationPoint(0.5F, -7.0F, -0.5F);
			bone62.addChild(cube_r98);
			setRotationAngle(cube_r98, 0.0F, -1.5708F, 0.0F);
			cube_r98.setTextureOffset(80, 123).addBox(-1.5F, 2.0F, -1.5F, 4.0F, 1.0F, 4.0F, 0.0F, true);
			bone = new ModelRenderer(this);
			bone.setRotationPoint(0.0F, -17.0F, 0.0F);
			bone.setTextureOffset(53, 24).addBox(-12.0F, 24.0F, -11.0F, 1.0F, 17.0F, 23.0F, 0.0F, false);
			cube_r99 = new ModelRenderer(this);
			cube_r99.setRotationPoint(-22.0F, 33.0F, -23.0F);
			bone.addChild(cube_r99);
			setRotationAngle(cube_r99, 0.0F, -1.5708F, 0.0F);
			cube_r99.setTextureOffset(45, 89).addBox(11.0F, -30.0F, -11.0F, 1.0F, 15.0F, 1.0F, 0.0F, false);
			cube_r100 = new ModelRenderer(this);
			cube_r100.setRotationPoint(-22.5F, 19.0F, -22.5F);
			bone.addChild(cube_r100);
			setRotationAngle(cube_r100, 0.0F, -1.5708F, 0.0F);
			cube_r100.setTextureOffset(65, 144).addBox(10.0F, -19.0F, -12.0F, 2.0F, 4.0F, 2.0F, 0.0F, false);
			cube_r100.setTextureOffset(56, 144).addBox(10.0F, -1.0F, -12.0F, 2.0F, 4.0F, 2.0F, 0.0F, false);
			cube_r101 = new ModelRenderer(this);
			cube_r101.setRotationPoint(0.0F, 40.0F, 0.0F);
			bone.addChild(cube_r101);
			setRotationAngle(cube_r101, 0.0F, 3.1416F, 0.0F);
			cube_r101.setTextureOffset(98, 106).addBox(10.0F, -18.0F, -13.0F, 3.0F, 3.0F, 23.0F, 0.0F, false);
			bone29 = new ModelRenderer(this);
			bone29.setRotationPoint(0.0F, 0.0F, 0.0F);
			bone.addChild(bone29);
			setRotationAngle(bone29, 0.0F, -1.5708F, 0.0F);
			cube_r102 = new ModelRenderer(this);
			cube_r102.setRotationPoint(-11.5F, 0.0F, 11.5F);
			bone29.addChild(cube_r102);
			setRotationAngle(cube_r102, 1.0021F, -0.7255F, -0.4941F);
			cube_r102.setTextureOffset(38, 144).addBox(-0.5F, -13.0F, -0.5F, 1.0F, 13.0F, 1.0F, 0.0F, false);
			cube_r103 = new ModelRenderer(this);
			cube_r103.setRotationPoint(-11.5F, 0.0F, 11.5F);
			bone29.addChild(cube_r103);
			setRotationAngle(cube_r103, 0.2707F, -0.5082F, 0.5615F);
			cube_r103.setTextureOffset(143, 80).addBox(-0.5F, -13.0F, -0.5F, 1.0F, 13.0F, 1.0F, 0.0F, false);
			bone25 = new ModelRenderer(this);
			bone25.setRotationPoint(0.0F, 0.5F, -9.5F);
			bone.addChild(bone25);
			cube_r104 = new ModelRenderer(this);
			cube_r104.setRotationPoint(1.0F, 32.5F, -13.5F);
			bone25.addChild(cube_r104);
			setRotationAngle(cube_r104, 0.0F, -1.5708F, 0.0F);
			cube_r104.setTextureOffset(102, 40).addBox(11.0F, -33.0F, -10.0F, 1.0F, 1.0F, 22.0F, 0.0F, false);
			cube_r105 = new ModelRenderer(this);
			cube_r105.setRotationPoint(1.0F, 32.5F, -14.0F);
			bone25.addChild(cube_r105);
			setRotationAngle(cube_r105, 0.0F, -1.5708F, 0.0F);
			cube_r105.setTextureOffset(102, 0).addBox(12.0F, -32.0F, -10.0F, 0.0F, 17.0F, 22.0F, 0.0F, false);
			bone51 = new ModelRenderer(this);
			bone51.setRotationPoint(0.0F, -17.0F, 0.0F);
			setRotationAngle(bone51, 0.0F, -1.5708F, 0.0F);
			bone51.setTextureOffset(53, 24).addBox(-12.0F, 24.0F, -11.0F, 1.0F, 17.0F, 23.0F, 0.0F, false);
			cube_r106 = new ModelRenderer(this);
			cube_r106.setRotationPoint(-22.0F, 33.0F, -23.0F);
			bone51.addChild(cube_r106);
			setRotationAngle(cube_r106, 0.0F, -1.5708F, 0.0F);
			cube_r106.setTextureOffset(45, 89).addBox(11.0F, -30.0F, -11.0F, 1.0F, 15.0F, 1.0F, 0.0F, false);
			cube_r107 = new ModelRenderer(this);
			cube_r107.setRotationPoint(-22.5F, 19.0F, -22.5F);
			bone51.addChild(cube_r107);
			setRotationAngle(cube_r107, 0.0F, -1.5708F, 0.0F);
			cube_r107.setTextureOffset(65, 144).addBox(10.0F, -19.0F, -12.0F, 2.0F, 4.0F, 2.0F, 0.0F, false);
			cube_r107.setTextureOffset(56, 144).addBox(10.0F, -1.0F, -12.0F, 2.0F, 4.0F, 2.0F, 0.0F, false);
			cube_r108 = new ModelRenderer(this);
			cube_r108.setRotationPoint(0.0F, 40.0F, 0.0F);
			bone51.addChild(cube_r108);
			setRotationAngle(cube_r108, 0.0F, 3.1416F, 0.0F);
			cube_r108.setTextureOffset(98, 106).addBox(10.0F, -18.0F, -13.0F, 3.0F, 3.0F, 23.0F, 0.0F, false);
			bone52 = new ModelRenderer(this);
			bone52.setRotationPoint(0.0F, 0.0F, 0.0F);
			bone51.addChild(bone52);
			setRotationAngle(bone52, 0.0F, -1.5708F, 0.0F);
			cube_r109 = new ModelRenderer(this);
			cube_r109.setRotationPoint(-11.5F, 0.0F, 11.5F);
			bone52.addChild(cube_r109);
			setRotationAngle(cube_r109, 1.0021F, -0.7255F, -0.4941F);
			cube_r109.setTextureOffset(38, 144).addBox(-0.5F, -13.0F, -0.5F, 1.0F, 13.0F, 1.0F, 0.0F, false);
			cube_r110 = new ModelRenderer(this);
			cube_r110.setRotationPoint(-11.5F, 0.0F, 11.5F);
			bone52.addChild(cube_r110);
			setRotationAngle(cube_r110, 0.2707F, -0.5082F, 0.5615F);
			cube_r110.setTextureOffset(143, 80).addBox(-0.5F, -13.0F, -0.5F, 1.0F, 13.0F, 1.0F, 0.0F, false);
			bone53 = new ModelRenderer(this);
			bone53.setRotationPoint(0.0F, 0.5F, -9.5F);
			bone51.addChild(bone53);
			cube_r111 = new ModelRenderer(this);
			cube_r111.setRotationPoint(1.0F, 32.5F, -13.5F);
			bone53.addChild(cube_r111);
			setRotationAngle(cube_r111, 0.0F, -1.5708F, 0.0F);
			cube_r111.setTextureOffset(102, 40).addBox(11.0F, -33.0F, -10.0F, 1.0F, 1.0F, 22.0F, 0.0F, false);
			cube_r112 = new ModelRenderer(this);
			cube_r112.setRotationPoint(1.0F, 32.5F, -14.0F);
			bone53.addChild(cube_r112);
			setRotationAngle(cube_r112, 0.0F, -1.5708F, 0.0F);
			cube_r112.setTextureOffset(102, 0).addBox(12.0F, -32.0F, -10.0F, 0.0F, 17.0F, 22.0F, 0.0F, false);
			bone54 = new ModelRenderer(this);
			bone54.setRotationPoint(0.0F, -17.0F, 0.0F);
			setRotationAngle(bone54, 0.0F, 3.1416F, 0.0F);
			bone54.setTextureOffset(53, 24).addBox(-12.0F, 24.0F, -11.0F, 1.0F, 17.0F, 23.0F, 0.0F, false);
			cube_r113 = new ModelRenderer(this);
			cube_r113.setRotationPoint(-22.0F, 33.0F, -23.0F);
			bone54.addChild(cube_r113);
			setRotationAngle(cube_r113, 0.0F, -1.5708F, 0.0F);
			cube_r113.setTextureOffset(45, 89).addBox(11.0F, -30.0F, -11.0F, 1.0F, 15.0F, 1.0F, 0.0F, false);
			cube_r114 = new ModelRenderer(this);
			cube_r114.setRotationPoint(-22.5F, 19.0F, -22.5F);
			bone54.addChild(cube_r114);
			setRotationAngle(cube_r114, 0.0F, -1.5708F, 0.0F);
			cube_r114.setTextureOffset(65, 144).addBox(10.0F, -19.0F, -12.0F, 2.0F, 4.0F, 2.0F, 0.0F, false);
			cube_r114.setTextureOffset(56, 144).addBox(10.0F, -1.0F, -12.0F, 2.0F, 4.0F, 2.0F, 0.0F, false);
			cube_r115 = new ModelRenderer(this);
			cube_r115.setRotationPoint(0.0F, 40.0F, 0.0F);
			bone54.addChild(cube_r115);
			setRotationAngle(cube_r115, 0.0F, 3.1416F, 0.0F);
			cube_r115.setTextureOffset(98, 106).addBox(10.0F, -18.0F, -13.0F, 3.0F, 3.0F, 23.0F, 0.0F, false);
			bone55 = new ModelRenderer(this);
			bone55.setRotationPoint(0.0F, 0.0F, 0.0F);
			bone54.addChild(bone55);
			setRotationAngle(bone55, 0.0F, -1.5708F, 0.0F);
			cube_r116 = new ModelRenderer(this);
			cube_r116.setRotationPoint(-11.5F, 0.0F, 11.5F);
			bone55.addChild(cube_r116);
			setRotationAngle(cube_r116, 1.0021F, -0.7255F, -0.4941F);
			cube_r116.setTextureOffset(38, 144).addBox(-0.5F, -13.0F, -0.5F, 1.0F, 13.0F, 1.0F, 0.0F, false);
			cube_r117 = new ModelRenderer(this);
			cube_r117.setRotationPoint(-11.5F, 0.0F, 11.5F);
			bone55.addChild(cube_r117);
			setRotationAngle(cube_r117, 0.2707F, -0.5082F, 0.5615F);
			cube_r117.setTextureOffset(143, 80).addBox(-0.5F, -13.0F, -0.5F, 1.0F, 13.0F, 1.0F, 0.0F, false);
			bone56 = new ModelRenderer(this);
			bone56.setRotationPoint(0.0F, 0.5F, -9.5F);
			bone54.addChild(bone56);
			cube_r118 = new ModelRenderer(this);
			cube_r118.setRotationPoint(1.0F, 32.5F, -13.5F);
			bone56.addChild(cube_r118);
			setRotationAngle(cube_r118, 0.0F, -1.5708F, 0.0F);
			cube_r118.setTextureOffset(102, 40).addBox(11.0F, -33.0F, -10.0F, 1.0F, 1.0F, 22.0F, 0.0F, false);
			cube_r119 = new ModelRenderer(this);
			cube_r119.setRotationPoint(1.0F, 32.5F, -14.0F);
			bone56.addChild(cube_r119);
			setRotationAngle(cube_r119, 0.0F, -1.5708F, 0.0F);
			cube_r119.setTextureOffset(102, 0).addBox(12.0F, -32.0F, -10.0F, 0.0F, 17.0F, 22.0F, 0.0F, false);
			bone57 = new ModelRenderer(this);
			bone57.setRotationPoint(0.0F, -17.0F, 0.0F);
			setRotationAngle(bone57, 0.0F, 1.5708F, 0.0F);
			bone57.setTextureOffset(53, 24).addBox(-12.0F, 24.0F, -11.0F, 1.0F, 17.0F, 23.0F, 0.0F, false);
			cube_r120 = new ModelRenderer(this);
			cube_r120.setRotationPoint(-22.0F, 33.0F, -23.0F);
			bone57.addChild(cube_r120);
			setRotationAngle(cube_r120, 0.0F, -1.5708F, 0.0F);
			cube_r120.setTextureOffset(45, 89).addBox(11.0F, -30.0F, -11.0F, 1.0F, 15.0F, 1.0F, 0.0F, false);
			cube_r121 = new ModelRenderer(this);
			cube_r121.setRotationPoint(-22.5F, 19.0F, -22.5F);
			bone57.addChild(cube_r121);
			setRotationAngle(cube_r121, 0.0F, -1.5708F, 0.0F);
			cube_r121.setTextureOffset(65, 144).addBox(10.0F, -19.0F, -12.0F, 2.0F, 4.0F, 2.0F, 0.0F, false);
			cube_r121.setTextureOffset(56, 144).addBox(10.0F, -1.0F, -12.0F, 2.0F, 4.0F, 2.0F, 0.0F, false);
			cube_r122 = new ModelRenderer(this);
			cube_r122.setRotationPoint(0.0F, 40.0F, 0.0F);
			bone57.addChild(cube_r122);
			setRotationAngle(cube_r122, 0.0F, 3.1416F, 0.0F);
			cube_r122.setTextureOffset(98, 106).addBox(10.0F, -18.0F, -13.0F, 3.0F, 3.0F, 23.0F, 0.0F, false);
			bone58 = new ModelRenderer(this);
			bone58.setRotationPoint(0.0F, 0.0F, 0.0F);
			bone57.addChild(bone58);
			setRotationAngle(bone58, 0.0F, -1.5708F, 0.0F);
			cube_r123 = new ModelRenderer(this);
			cube_r123.setRotationPoint(-11.5F, 0.0F, 11.5F);
			bone58.addChild(cube_r123);
			setRotationAngle(cube_r123, 1.0021F, -0.7255F, -0.4941F);
			cube_r123.setTextureOffset(38, 144).addBox(-0.5F, -13.0F, -0.5F, 1.0F, 13.0F, 1.0F, 0.0F, false);
			cube_r124 = new ModelRenderer(this);
			cube_r124.setRotationPoint(-11.5F, 0.0F, 11.5F);
			bone58.addChild(cube_r124);
			setRotationAngle(cube_r124, 0.2707F, -0.5082F, 0.5615F);
			cube_r124.setTextureOffset(143, 80).addBox(-0.5F, -13.0F, -0.5F, 1.0F, 13.0F, 1.0F, 0.0F, false);
			bone59 = new ModelRenderer(this);
			bone59.setRotationPoint(0.0F, 0.5F, -9.5F);
			bone57.addChild(bone59);
			cube_r125 = new ModelRenderer(this);
			cube_r125.setRotationPoint(1.0F, 32.5F, -13.5F);
			bone59.addChild(cube_r125);
			setRotationAngle(cube_r125, 0.0F, -1.5708F, 0.0F);
			cube_r125.setTextureOffset(102, 40).addBox(11.0F, -33.0F, -10.0F, 1.0F, 1.0F, 22.0F, 0.0F, false);
			cube_r126 = new ModelRenderer(this);
			cube_r126.setRotationPoint(1.0F, 32.5F, -14.0F);
			bone59.addChild(cube_r126);
			setRotationAngle(cube_r126, 0.0F, -1.5708F, 0.0F);
			cube_r126.setTextureOffset(102, 0).addBox(12.0F, -32.0F, -10.0F, 0.0F, 17.0F, 22.0F, 0.0F, false);
			bone26 = new ModelRenderer(this);
			bone26.setRotationPoint(0.0F, -16.5F, 0.0F);
			setRotationAngle(bone26, 0.0F, -1.5708F, 0.0F);
			cube_r127 = new ModelRenderer(this);
			cube_r127.setRotationPoint(0.0F, 0.0F, 0.0F);
			bone26.addChild(cube_r127);
			setRotationAngle(cube_r127, 0.0F, -1.5708F, 0.0F);
			cube_r127.setTextureOffset(0, 107).addBox(-0.5F, -0.5F, -11.0F, 1.0F, 1.0F, 22.0F, 0.0F, false);
			cube_r128 = new ModelRenderer(this);
			cube_r128.setRotationPoint(0.0F, 0.0F, -9.5F);
			bone26.addChild(cube_r128);
			setRotationAngle(cube_r128, 0.0F, 3.1416F, 0.0F);
			cube_r128.setTextureOffset(0, 107).addBox(-0.5F, -0.5F, -20.5F, 1.0F, 1.0F, 22.0F, 0.0F, false);
			bb_main = new ModelRenderer(this);
			bb_main.setRotationPoint(0.0F, 24.0F, 0.0F);
			bb_main.setTextureOffset(0, 0).addBox(-11.0F, -1.0F, -11.0F, 22.0F, 1.0F, 22.0F, 0.0F, false);
			bb_main.setTextureOffset(39, 69).addBox(-8.0F, -124.75F, -8.0F, 16.0F, 0.0F, 16.0F, 0.0F, false);
		}

		@Override
		public void render(MatrixStack matrixStack, IVertexBuilder buffer, int packedLight, int packedOverlay, float red, float green, float blue,
				float alpha) {
			Balloonstrip.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			Balloonstrip11.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			Balloonstrip12.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			Balloonstrip10.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			Balloonstrip2.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			Balloonstrip9.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			Balloonstrip7.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			Balloonstrip8.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			Engine.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			bone34.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			bone60.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			bone.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			bone51.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			bone54.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			bone57.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			bone26.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
			bb_main.render(matrixStack, buffer, packedLight, packedOverlay, red, green, blue, alpha);
		}

		public void setRotationAngle(ModelRenderer modelRenderer, float x, float y, float z) {
			modelRenderer.rotateAngleX = x;
			modelRenderer.rotateAngleY = y;
			modelRenderer.rotateAngleZ = z;
		}

		public void setRotationAngles(Entity e, float f, float f1, float f2, float f3, float f4) {
		}
	}

}
