
package studio.halbear.hem.itemgroup;

import studio.halbear.hem.block.BlueleafGrassBlockBlock;
import studio.halbear.hem.HemModElements;

import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.item.ItemStack;
import net.minecraft.item.ItemGroup;

@HemModElements.ModElement.Tag
public class BlueleafTabItemGroup extends HemModElements.ModElement {
	public BlueleafTabItemGroup(HemModElements instance) {
		super(instance, 63);
	}

	@Override
	public void initElements() {
		tab = new ItemGroup("tabblueleaf_tab") {
			@OnlyIn(Dist.CLIENT)
			@Override
			public ItemStack createIcon() {
				return new ItemStack(BlueleafGrassBlockBlock.block);
			}

			@OnlyIn(Dist.CLIENT)
			public boolean hasSearchBar() {
				return false;
			}
		};
	}

	public static ItemGroup tab;
}
