package studio.halbear.hem.procedures;

import studio.halbear.hem.block.AntsBlock;
import studio.halbear.hem.HemMod;

import net.minecraft.world.IWorld;
import net.minecraft.util.math.BlockPos;
import net.minecraft.block.Blocks;

import java.util.Random;
import java.util.Map;

public class AntHillUpdateTickProcedure {

	public static void executeProcedure(Map<String, Object> dependencies) {
		if (dependencies.get("world") == null) {
			if (!dependencies.containsKey("world"))
				HemMod.LOGGER.warn("Failed to load dependency world for procedure AntHillUpdateTick!");
			return;
		}
		if (dependencies.get("x") == null) {
			if (!dependencies.containsKey("x"))
				HemMod.LOGGER.warn("Failed to load dependency x for procedure AntHillUpdateTick!");
			return;
		}
		if (dependencies.get("y") == null) {
			if (!dependencies.containsKey("y"))
				HemMod.LOGGER.warn("Failed to load dependency y for procedure AntHillUpdateTick!");
			return;
		}
		if (dependencies.get("z") == null) {
			if (!dependencies.containsKey("z"))
				HemMod.LOGGER.warn("Failed to load dependency z for procedure AntHillUpdateTick!");
			return;
		}
		IWorld world = (IWorld) dependencies.get("world");
		double x = dependencies.get("x") instanceof Integer ? (int) dependencies.get("x") : (double) dependencies.get("x");
		double y = dependencies.get("y") instanceof Integer ? (int) dependencies.get("y") : (double) dependencies.get("y");
		double z = dependencies.get("z") instanceof Integer ? (int) dependencies.get("z") : (double) dependencies.get("z");
		double Random = 0;
		Random = Math.random();
		if (Random >= 0.1) {
			if ((world.getBlockState(new BlockPos(x + 1, y, z))).getBlock() == Blocks.AIR) {
				Random = Math.random();
				if (Random >= 0.75) {
					world.setBlockState(new BlockPos(x + 1, y, z), AntsBlock.block.getDefaultState(), 3);
				}
			}
			if ((world.getBlockState(new BlockPos(x - 1, y, z))).getBlock() == Blocks.AIR) {
				Random = Math.random();
				if (Random >= 0.75) {
					world.setBlockState(new BlockPos(x - 1, y, z), AntsBlock.block.getDefaultState(), 3);
				}
			}
			if ((world.getBlockState(new BlockPos(x - 1, y, z - 1))).getBlock() == Blocks.AIR) {
				Random = Math.random();
				if (Random >= 0.75) {
					world.setBlockState(new BlockPos(x - 1, y, z - 1), AntsBlock.block.getDefaultState(), 3);
				}
			}
			if ((world.getBlockState(new BlockPos(x + 1, y, z - 1))).getBlock() == Blocks.AIR) {
				Random = Math.random();
				if (Random >= 0.75) {
					world.setBlockState(new BlockPos(x + 1, y, z - 1), AntsBlock.block.getDefaultState(), 3);
				}
			}
			if ((world.getBlockState(new BlockPos(x - 1, y, z + 1))).getBlock() == Blocks.AIR) {
				Random = Math.random();
				if (Random >= 0.75) {
					world.setBlockState(new BlockPos(x - 1, y, z + 1), AntsBlock.block.getDefaultState(), 3);
				}
			}
			if ((world.getBlockState(new BlockPos(x + 1, y, z + 1))).getBlock() == Blocks.AIR) {
				Random = Math.random();
				if (Random >= 0.75) {
					world.setBlockState(new BlockPos(x + 1, y, z + 1), AntsBlock.block.getDefaultState(), 3);
				}
			}
			if ((world.getBlockState(new BlockPos(x, y, z + 1))).getBlock() == Blocks.AIR) {
				Random = Math.random();
				if (Random >= 0.75) {
					world.setBlockState(new BlockPos(x, y, z + 1), AntsBlock.block.getDefaultState(), 3);
				}
			}
			if ((world.getBlockState(new BlockPos(x, y, z - 1))).getBlock() == Blocks.AIR) {
				Random = Math.random();
				if (Random >= 0.75) {
					world.setBlockState(new BlockPos(x, y, z - 1), AntsBlock.block.getDefaultState(), 3);
				}
			}
		}
	}
}
